defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
files: {}
tailscale:
    providers:
        default:
            authKey: "<KEY HERE>"
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 80
log:
    level: info
    json: false
proxyaccesslog: true